name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: 
          - '7.4'

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@master
        with:
          php_version: ${{ matrix.php_version }}
          dev: "no"
      - name: get properties
        id: json_properties
        uses: ActionsTools/read-json-action@main
        with:
          file_path: "extension.json"
      - name: Move to folder
        run: |
          mkdir WikiMarkdown
          mv * .* WikiMarkdown/
      - uses: actions/upload-artifact@v3
        with:
          name: WikiMarkdown-${{steps.json_properties.outputs.version}}-PHP${{matrix.php_version}}
          path: |
            ./*
            !.*
            !DOCKER*
            !*.log
